language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

jobs:
  include:
    - stage: analysis
      php: 8.0
      before_script:
        - composer global require infection/infection
        - composer require --dev "roave/backward-compatibility-check:~6.0@dev"
      script:
        - composer psalm
        - composer bc-break
        - ~/.config/composer/vendor/bin/infection --min-msi=90

install:
  - travis_retry composer install

script:
  - composer tests
